### ISSUE TITLE
Section 4.1 "may"

### ISSUE THREAD

**Issue by Philip-Osterlund** [gryphonshafer/Quizzing-Rule-Book#100]
Why is the word ‘may’ included in this sentence: 
_Prior to a quizzer's answer being correct or incorrect, quizzers **may** have up to 30 seconds to provide their answer._

              - Remove it or clarify when a quizzer would not have 30 seconds to provide their answer.

**Comment by jttower** [comment]
If a quizzer has clearly given incorrect information and therefore would not be ruled correct (they say "Isaiah" instead of "Jeremiah"), then I don't personally understand why they would be given the full 30 seconds.  Then the quizzer just awkwardly stands there wondering what else to say, sometimes knowing they said the wrong thing because they answered too quickly, sometimes saying all sorts of incorrect and out of context things thinking the QM _might_ call them correct, etc. For this reason I think the word "may" is necessary.  

If we remove the word "may", then it would say "quizzers have up to 30 seconds to provide their answer", which I guess would be fine since it says "up to 30 seconds". I just wouldn't want it to seem like the quizzer MUST be given 30 seconds to answer, even if their answer is incorrect.

**Comment by jswingle** [comment]
I think this would be covered by the clause "prior to a quizzer's answer being correct or incorrect," though. Once the quizzer is clearly correct or incorrect, the answering period stops. If they're not clearly correct or incorrect, they have 30 seconds.

The "may" word was likely just imprecise language. I would support not only getting rid of the "may" word but also the "up to" phrase. I don't think the rulebook is confusing as written, but a little bit of extra precision is a good thing.

`"Prior to a quizzer's answer being correct or incorrect, quizzers have 30 seconds to provide their answer."`

**Comment by ARMediting** [comment]
I'd clarify it a little further: "Prior to a quizzer's answer being **_ruled_** correct or incorrect, **_a quizzer has_** 30 seconds to provide their answer." A quizzer may be correct or incorrect before being ruled as such, during which time they may continue to provide information. (The change to singular "quizzer" is just for continuity across the sentence.)

**Comment by jswingle** [comment]
@ARMediting that ruling is even better, +1

**Comment by jttower** [comment]
Rules Committee voted on 3/20/22 to adopt this new wording: 
"Prior to a quizzer's answer being ruled correct or incorrect, a quizzer has 30 seconds to provide their answer."
Vote passed 6-0.
On behalf of the Rules Committee, this issue is closed.
