### ISSUE TITLE
4.2.3 - Quiz-Out

### ISSUE THREAD

**Issue by Philip-Osterlund** [gryphonshafer/Quizzing-Rule-Book#101]
The Quiz-out rule seems to be out of place.  Suggestion: Move it after the 4.2.3.1 example.
(NCD DQLT suggestion)

**Comment by jttower** [comment]
At first glance, the statement "A quizzed-out quizzer may only jump on bonus questions" seems out of place before 4.3.2.1.  I discovered that in the minimalist and reference renders of the current rule book, the preceding phrase:

**Quiz-Out
    4 correct questions by the same quizzer in the same quiz** 

is left out, which makes the "quizzed-out quizzer" statement seem really out of place.  The same is true in 4.2.4 where it references an err-out.  I know this is because those renders of the rule book either removed or moved the terms/definitions.  However, when those are taken out and other statements are left in, it seems confusing and out of place.  

In the full-content render of the rule book, I think the placement of the Quiz-out and Err-out rules are in the right places.  I think the minimalist and reference renders need those terms in those places in order to make sense in context.  

Can we have a render that contains the terms/definitions but leaves out the logic?  For someone who is new to quizzing it doesn't necessarily make sense to print out the full-content render of the rule book because they don't need the computer logic. But it is important for them to have the terms within the context of the rules rather than at the end in an appendix.

**Comment by kclimenhaga** [comment]
That sounds good to me.
