### ISSUE TITLE
4.5 Fouls

### ISSUE THREAD

**Issue by ghost** [gryphonshafer/Quizzing-Rule-Book#102]
Does a quizzer also have to sit out Toss-up and Bonus numeric questions (in questions 1-15)? 
 - This is not specified but would seem to be the same consequence as otherwise specified (but for questions 16-20 which have alphanumeric questions).

- We otherwise think the consequence of a Foul should only apply to the quizzer called for the Foul and not the substitute (i.e. the chair).
-  The team is already penalized by the foul and the possible point deduction.

(There is a question/disagreement as to if the chair should be punished, or just the individual quizzer.)

**Comment by ARMediting** [comment]
Philip, I'm a bit confused what you're asking about or what you feel is unclear. Are you suggesting a change be made to wording, or to the content of this rule?

**Comment by scottpeterson** [comment]
A team should not be able to "get out of a foul" via substitution. I think it's a small thing, but I'm in favor of the current rule, the chair remaining punished for the remainder of the numbered question.

**Comment by jttower** [comment]
I think what Philip is getting at is that on questions 16-20 the fouled quizzer might potentially have to sit out for 3 questions (foul on 16, sit out for 16, 16a, and 16b if there is a toss up and bonus), but on questions 1-15 the way it reads now is that they would only sit out for one question (foul on 3, back in on 4 even if there is a toss up or bonus). Maybe he is suggesting that the rule be modified so that the consequence of a foul is the same regardless of the question number.  

- The quizzer upon whom a foul is called becomes ineligible to jump on that question number, including any alphanumeric question numbers. The chair remains ineligible to jump on that question number, including any alphanumeric question numbers, even if the quizzer who committed the foul is substituted for.
Perhaps change to:
- The quizzer upon whom a foul is called becomes ineligible to jump on that question number, including any subsequent toss up and bonus questions. The chair remains ineligible to jump on that question number, including any subsequent toss up and bonus questions, even if the quizzer who committed the foul is substituted for.

Either that or change it so that the quizzer only sits out for that one question they fouled on (regardless of question number) so that it is consistent.  

And I agree with Scott that the chair should be penalized, otherwise a team could call a time-out and take the fouled quizzer out, which invalidates the consequence.

**Comment by ARMediting** [comment]
If we changed it, I'd prefer to switch to sitting out just the one question, regardless of number/letter. I'd rather not make teams have a chair be out for three whole question numbers.

**Comment by JoshJetto** [comment]
I agree with Alex's preferred change. Usually, fouls are not intentional or flagrant, and for the penalty to be as stiff as three questions and potentially a missed chair bonus is very severe. If we did leave fouls as counting against the subsequent toss-up and bonus question, I would prefer the foul be charged to the individual and not to the chair. My guess is that in about half of the foul situations, a substitution would not be possible, since it would occur after the question type is announced (e.g. - a light on after question is called or a too-early reference jump), so a team could not call a timeout on that question to do a substitution. However, even in other foul scenarios, that a team is forced to call a timeout and do a substitution in order to get the chair back in is (except on question 20 only) a high price to pay, because the team is likely subbing a weaker quizzer in for a stronger quizzer and the substituted quizzer has to remain out of the quiz for at least three numbered questions before they can be brought back in, which would cost a team their second timeout. I say, let's let the teams make those kind of cost-benefit decisions. I think it makes the quizzing more interesting.

**Comment by jswingle** [comment]
I'm kind of torn because I like consistent rules:

On the one hand, it's nice and consistent that a foul = wait until the next question number.

On the other hand, it would be nice and consistent if we changed it so that a foul always has the same "effect" on the quizzer regardless of when in the quiz it's performed. The reason why we complicate quizzing with A and B questions at the end has to do with maintaining the competitive balance regarding errors - I don't see any reason why fouls should be considered.

I could be swayed either way with a new argument, I think. I'm mostly indifferent but leaning 1% in the direction of changing it.

**Comment by kclimenhaga** [comment]
I'm also fairly indifferent since fouls happen so seldom. My inclination would be to change it so that they are only out for that question, not the A/B.

**Comment by ARMediting** [comment]
After thinking some more, I feel more in favor of keeping the rule as it is, at least for now. It'd be a fairly impactful change to make this year, and if 16-20 are purposefully structured differently, shouldn't that apply to fouls as well?

**Comment by jttower** [comment]
Rules Committee voted on 3/20/22 to continue to discuss this issue.

**Comment by jswingle** [comment]
Revisiting this issue -- I still lean toward changing it to fouls only penalizing for one question (not one "question number") but still don't have an extremely strong opinion about it. I think the advantage of changing it is that a foul on 16-20 could lead to a quizzer having to sit out a Bonus for a relatively minor infraction. If a quizzer's talking during a question then I have no problem with a harsh penalty, but sitting out all of 16, 16A, and 16B for accidentally triggering one's light early seems like overkill.

**Comment by jswingle** [comment]
Language change proposal, under "4.5 Fouls":

Original:
```
The quizzer upon whom a foul is called becomes ineligible to jump on that question number, including any alphanumeric question numbers. The chair remains ineligible to jump on that question number, including any alphanumeric question numbers, even if the quizzer who committed the foul is substituted for.

...

3 fouls by a quizzer eliminate that quizzer from the quiz. The quizzer must leave the platform immediately. That seat will continue to be ineligible to jump for the entire question number, including any alphanumeric question numbers.
```

Proposal:
```
The quizzer upon whom a foul is called becomes ineligible to jump _on that question_. [remainder deleted]

...

3 fouls by a quizzer eliminate that quizzer from the quiz. The quizzer must leave the platform immediately. _If a substitute replaces the fouled-out quizzer, the substitute may not jump until the next question._
```

**Comment by jttower** [comment]
I like this proposal. I think it makes it more concise and more clear.

**Comment by jttower** [comment]
On behalf of the Rules Committee:

During our meeting on 9/11/2022, the Rules Committee voted 5-0 to approve the change detailed below. This means that a "pull request" has been made - in other words, a change has been officially proposed and voted on by the Rules Committee, and will be given a final vote in 3 months.

As noted above, the change is:
----------------------------
_**The quizzer upon whom a foul is called becomes ineligible to jump on that question. [remainder deleted]
...
3 fouls by a quizzer eliminate that quizzer from the quiz. The quizzer must leave the platform immediately. If a substitute replaces the fouled-out quizzer, the substitute may not jump until the next question.**_
-----------------------------

The change is that a quizzer is only fouled for that individual question.  We felt that punishing the quizzer/chair for any remaining A and B questions is unnecessary. We do want to make sure that veteran quizzers/coaches/officials are all clear on this change so there will be no confusion going forward.  

For more information on the rulebook Change Management Process, please visit: https://github.com/gryphonshafer/Quizzing-Rule-Book/blob/master/content/rule_book/change_management.md
