### ISSUE TITLE
1.2.2.2 Multiple Answer (MA) - on behalf of Josh Jetto

### ISSUE THREAD

**Issue by ZacharyTinker** [gryphonshafer/Quizzing-Rule-Book#105]
Current Rule: 
Must meet all the requirements of an INT except for the single answer requirement
Must have more than 1 answer
•	The clarification of a single answer does not meet the above requirement
•	The identification of a single pronoun does not meet the above requirement
•	The identification of a plural pronoun, with more than 1 clarification to the pronoun, does meet the above requirement

In addition, an MA question is invalid if 1 of the listed answers to the multiple answer's questions is a "negative" answer. A "negative" answer is an answer used to contrast another answer or an answer that does not answer the question, such as an answer that begins with the words or similar words to "not" or "neither".
1.2.2.2.1. Examples
For an example of a negative word, consider 1 Corinthians 3:7:
So neither the one who plants nor the one who waters is anything, but only God, who makes things grow.
The question "Who is anything?" would require the answer:
Neither the one who plants nor the one who waters.
This is an invalid MA.
Consider 1 Corinthians 9:25:
Everyone who competes in the games goes into strict training. They do it to get a crown that will not last, but we do it to get a crown that will last forever.
The question "A crown that will what?" with an answer "Not last; last forever" is an invalid MA.

Proposed Change:  
Removal of everything from “In addition…” forward, including the examples.

Rationale: The exclusion of all negative answers from MA question types, I think, is an overreaction to the fact that sometimes a negative answer does not answer the question and should not be valid. However, many times they are valid. Even the second example given in the rulebook should be a valid MA question - "A crown that will not last" is a type of crown defined by its temporary character even as "a crown that will last forever" is defined by its eternal character; these are two different crowns! Also, this rule also makes Romans 8:38-39, one of the great Scripture verses about our inseparable standing in Christ from the love of God, unusable as an MA ("What will be able to separate us from the love of God that is in Christ Jesus our Lord?"). Again, I think this is a rule that overreaches in that it is attempting to correct a situation for some verses that someone might pull as an MA by eliminating all - even good - negative answers from the question pool of MAs. It throws the baby out with the bath water.

**Comment by kclimenhaga** [comment]
I agree in principle that this rule should be adjusted as you describe. However, if we are making a separate best practice document, I think we should say something about "if a question can be worded in two ways, and one of the two ways would provide a negative answer, write it the other way". I agree that Romans 8:38-39 should be used as a MA, however in the 1 Corinthians 9:25 example, I do not think it is a very strong question as worded. I would instead write this question as "What crown?" You are correct that "a crown that will not last" is a type of crown, but the question "A crown that will what" is not asking "What crowns are there?", but rather "What will the crown do?" If I encounter the question written as "A crown that will what", I'm fine with the rule book saying to keep it, but I would like to see a best practice encouraging us to avoid those questions where possible.

**Comment by gryphonshafer** [comment]
As a technical aside: The rule book committee (RC) can address the idea of best practices a few different ways, if they want. You could have a separate document, or you could have intermixed sections that are optionally filtered (like "Commentary" sections). Or you could elect to do both, which is to say, you write up best practices as sections in context that are filtered and merged into a stand-alone document.

I'm agnostic as to which of these is the best practice for best practices. :) But I worry a separate document might become ignored over time.

**Comment by jswingle** [comment]
I have just closed the issue: https://github.com/gryphonshafer/Quizzing-Rule-Book/issues/95 as it is an identical issue to the one presented here.

Please reference the discussion over there as part of the discussion on this issue. Here's my thorough explanation of my own thoughts on this rule: https://github.com/gryphonshafer/Quizzing-Rule-Book/issues/95#issuecomment-1033168925

**Comment by jswingle** [comment]
I would like to progress this issue and get a vote on it at some point before the 2023 revisions are presented to the CQLT. There is no language proposal necessary since we are only _deleting_ rules, but since we are deleting rules in several places, I've aggregated everything into this one post.

Here is the proposal:

Section 1.2.2.2 --
The entire paragraph beginning with "in addition" will be deleted.

Section 1.2.2.2.1 --
The entire section will be deleted.

Section 1.2.3 --
The bullet point "if the question is not answered" will be deleted.

Section 1.2.3.1 --
The entire section will be deleted.

--

Additional explanation on section 1.2.3 -- while it is true that a question should be deemed invalid "if the question is not answered," the intent of this language was to exclude negative answers to questions. This is a mismatch between intent and function, because negative answers _do in fact_ constitute an answer to a question. 

I think we should just delete the bullet point, because we already have the bullet point deeming a question invalid if it is "ambiguous, tricky, or misleading." If the printed answer to a question doesn't actually match with the printed question, that makes the question ambiguous and no official is going to be confused about whether or not to throw it out. So the simplest solution is to delete this bullet point rather than attempt a rewording.

**Comment by jswingle** [comment]
I have closed out issue #27 because I think it is inextricably linked to this issue, and the proposal I've written above would also solve that issue.

**Comment by ARMediting** [comment]
I could go either way on this. It does feel like something more under the purview of question writers—they should be able to write MAs that may include "nots" that make logical sense and avoid misleading quizzers and the audience. But with MAs making up such a small percentage of a quiz, do we need to worry about the pool size?

Also, does anywhere in the rulebook, especially under "Invalid Questions," explicitly state that if the question has some sort of typo or misprint that leads to a misreading or misruling, it should be thrown out? I can make a separate issue if so. I was just trying to come up with another scenario where "the question is not answered."

(Note that all the rulebook references above are now 2... instead of 1....)

**Comment by kclimenhaga** [comment]
After discussion by the rule book committee, the decision was made to adopt Jeremy's proposal, which I am summarizing as:

- The MA "negative answer" rule will be deleted, along with its example.
- The INT "If the question is not answered" bullet point under Invalid Questions will be deleted, along with its example.
