### ISSUE TITLE
2.2.1.1.1 Reference Questions - on behalf of Josh Jetto

### ISSUE THREAD

**Issue by ZacharyTinker** [gryphonshafer/Quizzing-Rule-Book#107]
Current Rule: 
“On a Reference type question, if the quizzer has given all the information in both the question and the answer and the complete question was not read, the quizmaster will ask, ‘What is your question?’”

Proposed Rule:
“On a Reference type question, if the quizzer has given all the information in both the question and the answer and no part of the interrogative or Scripture text portion has been spoken by the quizmaster (i.e. – only part of or the whole of the reference portion of the question had been read before the quizzer jumped), then the quizmaster will ask, ‘What is your question?’”

Rationale: See previous rationale for Rule 1.2.2.3

**Comment by ARMediting** [comment]
Is this to delineate the verse number from the interrogative/Scripture, because "More" is needed if the verse number isn't finished? Since the verse number comes before the interrogative, "What is your question?" will always be needed if the complete question was not read, so I think that wouldn't be a reason to change this. I think it would be helpful to restate the "More" rule for in 2.2.1.1.2.

**Comment by ARMediting** [comment]
Okay, I read the 1.2.2.3 issue, and now I see how this applies.

**Comment by jswingle** [comment]
Closing this issue and continuing the discussion in issue #106 instead.
