### ISSUE TITLE
3.4 Question Type Distribution - on behalf of Josh Jetto

### ISSUE THREAD

**Issue by ZacharyTinker** [gryphonshafer/Quizzing-Rule-Book#108]
Current Rule: 
Narratives		Epistles
INT	8-14			9-16
FTV	3-4			3-4
Q	2-3			3-4
Ref	3-6			3-7
MA	1-2			1-2
SIT	2-4			0

Tot:	19-33			19-33

Proposed Rule:
Narratives		Epistles
INT	8-16			8-16
FTV	3-4			3-4
Q	1-3			1-3
Ref	2-4			2-4
MA	2-3			2-3
SIT	2-4			0

Tot:	18-30			16-30

Rationale: 
For reference, I am including the 2013 rulebook question distribution below:

2013 Rulebook
Narratives		Epistles
INT	8-12			8-12
FTV	2-3			2-3
Q	1-2			1-2
Ref	3-5			3-5
MA	2-7			2-7
SIT	2-4			0

Tot:	18-33			16-29

The rationale for this change is divided into three sections:
1) Quote and Reference question changes
2) Multiple Answer changes
3) Total Minimum Question changes

1) Quote and Reference question changes
The current rule mandates in Narrative material years that a minimum of 25% and a maximum of 39% of questions asked in a quiz must be a Quote or Reference question. In Epistle years that number is even higher – 30%-46%. This is way, way too high. How important is it, Biblically, to know where a Scripture is by the chapter and verse reference? What does our current distribution say about the importance of that? Biblically speaking, how important was it for the writers of the New Testament to know “Chapter and Verse” when they were quoting the Old Testament?

The versification of the New Testament didn’t come around until 1551. For the first 1,500 years the New Testament was in existence and used by the Holy Spirit to lead people into the obedience of faith in Jesus, there were no verse numbers and no chapters. The versification of the text is not inspired by the Holy Spirit, so we should not be so highly incentivizing Quote and CVR question types. By our very heavy reference distribution, we are communicating that knowing Scripture by the non-inspired reference system is extremely important. In fact, the chapter and verse divisions sometimes obscure the meaning of Scripture as people automatically disconnect what is happening before a chapter break from what comes after it. In one of John Stumbo’s video blogs last year, he actually mentioned that with regard to the connection between 1 Corinthians 13 and 1 Corinthians 14:1.

 _You can advance the video to 9:59. He talks about this devotionally for the last two minutes of the video blog._

The fact that you can make lots and lots of CVR questions (of the 5,700 total questions in the District Set, just over 2,000 are Reference-type) does not justify having more of them in every quiz. The reason you can make lots of CVR questions (as opposed to other question types) is because CVR questions are by nature short, vague, and use common language – “He will what?” for example. How important is it for students to know that in Matthew 12:18 “He will proclaim justice to the nations” but in Matthew 12:19 “He will not quarrel or cry out” but in Matthew 12:20 “He will not break a bruised reed”? Isn’t more important for them to know that in Jesus this prophecy that came through Isaiah is fulfilled in its entirety, and to simply know what the text says in these three verses rather than having to devise a way to remember and give great energy to remembering in which numbered verses it says “he will” do specific things? Why are we putting so much focus on and incentivizing kids to pour so much effort into knowing the Scripture by the non-inspired reference system when that effort would be better poured into knowing the inspired text itself? Shouldn’t we be incentivizing that more and not less? The above proposed rule change does just that, while keeping Quotes and Reference Questions viable specialties at the District and International levels (15%-32% in Narrative years and 15%-35% in Epistle years).

For 95-98% of quizzers, the current reference-heavy question distribution means that they are essentially locked out of more and more questions, unless they have both the time and the natural ability for cold-recall of numbers instead of text clues. Locally, this results in large numbers of un-jumped on questions as well as boredom and discouragement with quizzing, because there are fewer questions they can answer, which means that under the current distribution, Bible quizzing is producing less motivation to memorize and read and study the word of God than it otherwise could. Not only that, but a Quote and Reference-heavy distribution creates higher barriers to successful participation by greater numbers of potential quizzers (and potentially very good quizzers), which, again (as I said in my rant under 1.2.2.3) actually lowers the competitive level locally and Internationally.

2) Multiple Answer changes
The current distribution makes Multiple Answer questions a virtual non-entity among the specialty questions. This puts quizzers who are not reference quizzers at a further disadvantage to those who are. MAs are more difficult to answer than INTs, and in that, they encourage quizzers to know the inspired text better. They are also found in a significant number of verses in the text. Separating MAs from CVRMAs and CRMAs was a good move as these are two very different kinds of specialties. However, lowering them down to 1-2 in the distribution was a swing too far of that pendulum. It has been argued that MAs are too easy of a specialty to master (because there are fewer MAs in the question pool than some other questions), so we should have very few of them. To that argument I would pose several questions and comments: 

1) Is the average MA question and answer more or less significant than the average CVR or CR?
2) If learning the specialty is so easy to master, then it would follow logically that more quizzers (at the International level) would have that specialty mastered, so wouldn’t that make them more difficult as a question type for any one individual to score on?
3) The number of Situation questions in the database is slightly lower than the number of MA questions. Why should there be twice as many Situations asked in Narrative years than MAs? Shouldn’t these be somewhat comparable? Aren’t Situations just as easy (or easier, given that there are multiple Situation questions in the database for the same quotation) a specialty for International quizzers to master as MAs? 

MAs are more significantly distinct from INTs than CVRMAs and CRMAs are from CVRs and CRs and should be their own specialty category (and thus, should have a higher distribution than the current rulebook) for at least two reasons: 

 _I quizzed at Internationals 6 years and was a pretty decent competitor, and I never had the material referenced. Under the current distribution, as someone whose brain recalls better from the text than from the reference system, this reference system would have hurt my ability to compete as well as I did, because of the sheer number of questions I would have been locked out of._

**Comment by jswingle** [comment]
Agreed on MA. 2-7 was way too much, but 1-2 was an overcorrection. I think 2-3 is great, but would suggest possibly a 2-4 or even 3-4 on epistle years when we don't have SITs? I think we run the risk of having too many INTs in epistle years if we don't allocate a little more to the specialty types. 

Agreed completely on Quotes. There are way too many of those now. Perhaps we could do 2-3 on epistle years, in line with my sentiment above on MAs. Not sure.

As for References, I think we should consider splitting off the min/max distribution into two, and slightly emphasizing CRs over CVRs (because CRs have a much more significant purpose, pedagogically, than CVRs). But this discussion would fit better on a separate issue, I think.

I'm torn on CVRs as far as importance goes. At higher levels of competition, when quizzers jump on just the reference, I think they become impressive tests of skill and material knowledge as the quizzer works through the verse carefully to find the question. But at lower levels of competition, a ton of "he will what?" CVRs don't seem to have much of a purpose.

**Comment by jttower** [comment]
I think 2-3 MAs would be fine.  I agree that 1-2 is too few, but up to 7 is WAY too many. 

I agree with what Josh is saying about too many Reference questions.  I think these can show impressive competency at higher levels like Jeremy was saying, but as far as the goal and mission of Quizzing, I don't think knowing the difference between "He will what" in different chapters is necessarily going to help you spiritually down the line.  These are the minutiae of quizzing that some really get into, but I don't think it furthers the goal.  (Sorry, all you CVR/CR people!)

I don't think we should be reducing the number of Quote questions for a few reasons:

1. This is only one of two question types that require word perfect answers, and we want quizzers to know and remember the Word of God accurately.  
2. If we are talking about quizzing being a ministry that promotes memorization, then just having them know key words and minute differences between similar statements in chapters isn't memorizing the material in order to hide it in their heart. Memorizing lists (for MAs), similar questions in different chapters (for Refs), or key words (for INTs), I would argue, isn't the same as memorizing verses.  
3. Contrary to Josh's argument about verse numbers, although they are not inspired and were added later, they do make it easier to find the verse.  If you are witnessing or talking to someone and try to reference a verse, it is much better if you know where to find it.  If we are trying to help our teens to become Biblically literate, then knowing where to find a verse goes a long way.  (I wish I could remember more references!)
4. I agree that some people are not as good at remembering the "address" of a verse.  This is why Finish type questions are extremely valuable because it still requires them to memorize the verse, but not necessarily know the reference. 
5. I don't think that Ref, MA, or SIT questions are spiritually more valuable than Quotes. 

Maybe a fair medium could be:
Narratives    Epistles
INT  7-15       7-15
FTV  3-4        3-4
Q     2-3        2-3  
Ref   2-4        2-4  
MA   2-3        2-3
SIT    2-4        0

Tot: 18-33     16-29

Personally, I like the idea of the number of min/max questions being the same every year (with the exception of adding in SITs).

**Comment by JoshJetto** [comment]
The rest of my rationale for keeping MAs separate from INTs got cut off in the original issue post. Here is the rest of it. The first part is not artfully worded, but the numbered rationale gets at the reasoning.

MAs are more significantly distinct from INTs than CVRMAs and CRMAs are from CVRs and CRs and should be their own specialty category (and thus, should have a higher distribution than the current rulebook) for at least two reasons: 
1) There are very, very few CVRMAs and CRMAs annually in the question databases. In John, the CMA District question set had a total of 67 - 20 CRMAs and 47 CVRMAs out of 3,016 questions. By contrast, there were 219 MAs in the database. 
2) Nobody (really) specializes in CVRMAs. They specialize in CVRs and learn the CVRMAs along with them, because there are so few of them and because the prompt for jumping on both of these question types is the same – it’s simply the chapter-and-verse reference. By contrast, the prompts for MAs and INTs, are widely varied because they come from the text itself. And unlike CVRs, nobody (really) specializes in INTs, because there are far too many of them (and because, unlike CVRs, they can be asked in such a wide variety of ways that it would be a waste of time to try to learn all of the possible text-prompt points to do that). In other words, INTs to MAs is not the same as CVRs to CVRMAs such that you could say to an International quizzer (or one at the local or District level), “Say, while you’re working on specializing in INTs, why don’t you just pick up the MAs at the same time.” 

MAs themselves have enough standing in the text to merit their own specialty status with an appropriate number of questions in the distribution to incentivize local quizzers to take notice of them in the text and to learn them from the text as they study as well as for International quizzers to commit the time needed to master them for that competition. The proposed distribution of a minimum of 2 and a maximum of 3 per quiz reflects and restores that.

**Comment by scottpeterson** [comment]
Are you saying that the proportion of written questions should dictate the asked distribution? CRs would be 1/4 of the asked questions then. 

I would think we would set the minimums and maximums based on what we want to reward and incentivize, and not on what is most commonly written.

**Comment by jswingle** [comment]
@ZacharyTinker @JoshJetto @scottpeterson @jttower What do you all think about closing out this issue and linking it in this other issue? https://github.com/gryphonshafer/Quizzing-Rule-Book/issues/99

I've been combining identical issues on my own initiative, but I thought I'd ask you all since there's already a long discussion here that I don't want to get buried.

**Comment by scottpeterson** [comment]
Thanks for asking the question. I think just closing it without asking (because there's no expectation yet) could seem to the Author and Commenters that they're getting buried. 

People will never read all existing Issues to see if there's a duplicate when creating their own. BUT, I don't like (a) a rule not letting people open an Issue unless a member of the RC approves, or (b) anyone can open Issues but no one is supposed to comment until someone on the RC post "not a duplicate, carry on"--both of those seem like too much unneeded red-tape that'll slow things down. 

I think the best course of action is to allow a member of the RC to just link and close any duplicate, leaving the original open--and state that clearly. So in this case because Josh/Zach opened 108 on 4/7 and Phillip opened 99 on 4/6, this one would get closed (and 99 would have a link to this). 

So if you're an Author of a duplicate that just gets closed by a member of the RC, it's on you to navigate to the original, and add your thoughts there.

**Comment by JoshJetto** [comment]
Yep, was thinking the same thing.

Josh

**Comment by jswingle** [comment]
Looks like we had this discussion back in February but I neglected to go in and close the issue. Here's the link to the old issue:

https://github.com/gryphonshafer/Quizzing-Rule-Book/issues/99
