### ISSUE TITLE
4.2.1 Context Application clearer wording

### ISSUE THREAD

**Issue by jswingle** [gryphonshafer/Quizzing-Rule-Book#120]
This proposal concerns the following rule:

```
4.2.1. Context Application:
"On all question types, a quizzer cannot automatically be ruled out of context by a single word, even if it is a unique word..."
```

This rule as written is a bit ambiguous, and relies heavily on how one interprets the word "automatically." My interpretation of this rule is that one word cannot _automatically_ take a quizzer out of context, but _depending on the overall situation_ it may be the case that a single word is the difference between being in context and being out of context.

To illustrate, here's a hypothetical example. Let's say one verse uses the phrase "the Bread of Life", while another verse out of context uses "the Word of Life." If a quizzer jumps and says "the Word of Life" when answering a question about the verse that says "the Bread of Life," I think this should be considered out of context. They're using an entire phrase and title which belongs to a separate context. But, many others look at this rule and apply it differently, saying that since there's only a one word difference, this would be ruling a quizzer "out of context by a single word."

If that's the case, we should fix up the language to reduce confusion, because I don't think that's the _intent_ of this rule. My guess is that the whole point of this rule was to prohibit officials from finding "gotcha" ways to rule a quizzer out of context - for example, when the word "till" is a unique word and the quizzer says it in another context where the word is supposed to be "until." Quizzers should certainly not be ruled out of context for that, but if changing even a single word makes the entire phrase or concept something out of context, we shouldn't be afraid to rule the quizzer incorrect.

My interpretation of the intent could be off, though, and maybe others have an idea for a different direction to go with the context rule.

**Comment by scottpeterson** [comment]
I completely agree. A one word delta in the midst of a multi word word perfect phrase is very different than a word said in isolation, or a word said in a multi word not word perfect phrase.

**Comment by jttower** [comment]
In the hypothetical example given above, I'm guessing "The Bread of Life" and "The Word of Life" wouldn't be used in the same chapter (if you can find a different example, let me know), and definitely not in the same "section". The only other "Life" title I can think of is "The Way, the Truth, and the Life", which is in John 14:6, while "The Bread of Life" is used in John 6:35.  Another similar title is "The Light of the World" used in John 8:12, which also has the phrase "the light of life".   These titles/phrases are used in very different contexts and answer different questions, so I would agree that a quizzer would be incorrect if using one of these phrases in the wrong context, even if the wording is similar. 

In response to @jswingle and the protest last year (mentioned in #116 ), I think it was partially due to "automatically", partially due to a slightly different name of someone (the tempter, the devil, Satan in Matthew 4:1-11), and partially due to "in context" meaning 5 verses.  In this case the quizzer said all three names (I don't remember in which order).  All three names are used interchangeably in the section, tempter being a unique word in verse 3, Satan being used once in verse 10 (not a unique word), and the devil being used 4 times (verses 1, 5, 8, and 11).  

I don't remember the exact question, so let's say it was a SIT question asking who said it in verse 9.  With the current rule, if I'm understanding correctly, the quizzer would be okay if they said the devil (verse 8 and 11), or maybe you would want them to say Satan (verse 10).  They would be called wrong if they said the tempter (verse 3), not necessarily because it is a unique word, but because that is 6 verses from verse 9.  You could also flip this example and say it was a SIT question on verse 3 with the answer of the tempter, and if they said Satan (verse 10), then they are wrong. However, I assert that the quizzer should be called correct for several reasons: 
1. Since all three names are the same person, they haven't given incorrect information (i.e. a different person).  
2. Since one word can't put you out of context (even a unique word), then they aren't wrong.  
3. It's not the same thing as answering with other titles of Satan used elsewhere in the material that are clearly out of context, like "Beelzebul", used in Matthew 12:24 or "the enemy" used in Matthew 13:39. 
4. Since all three names are used in the same section on Jesus' temptation, I would argue they are in context (see below).

To me this is different than the examples in John, where the titles are in different chapters and clearly different contexts.  In the Matthew example, it is all in one section, clearly in the context of the narrative of Jesus being tempted. And if, as @JoshJetto has mentioned, the verse numbers are not inspired, then being 5 verses or 6 verses away should not necessarily determine the context of the text, which relates to #56 and #38 .

**Comment by gryphonshafer** [comment]
Just as a historical note: Back in the mid-1990s, context in PNW was de facto the NIV section headers. It wasn't in the rule book and was totally a tribal thing, but it was a thing. It's why CBQZ to this day shows those little paragraph markers to denote the beginning of a new section.

Switching from 5 verses to section headers would be an improvement because at least the section headers aren't arbitrary. A group of people thought about where concept breaks were (even though they were often wrong).

That said, I think an even better solution is to remove context entirely, for reasons others have already stated.

**Comment by jswingle** [comment]
I'm closing out this issue since it is more or less identical with this one that was posted earlier: https://github.com/gryphonshafer/Quizzing-Rule-Book/issues/38
