### ISSUE TITLE
MACVR/MACR vs. CVRMA/CRMA

### ISSUE THREAD

**Issue by jttower** [gryphonshafer/Quizzing-Rule-Book#127]
In the current rule book, why are Reference questions with a MA listed as MACVR and MACR instead of CVRMA and CRMA?  It seems the MA should come after the CVR/CR since it is a subtype of reference questions.  Furthermore, when a QM announces this question type I'm fairly certain they say "a chapter verse reference question with a multiple answer", I don't think they say "this is a multiple answer question with a chapter verse reference", which would indicate that it is a subtype of MA.

I propose that in every place in the rule book where it says MACVR/MACR, it be replaced by CVRMA/CRMA.

**Comment by gryphonshafer** [comment]
In English, an adjective precedes a noun. (By contrast, in French, an adjective follows a noun.) This is why reference questions are CVR instead of RCV.

**Comment by scottpeterson** [comment]
I would like to ❤️➕💯 ❤️➕💯 ❤️➕💯 ❤️➕💯 ❤️➕💯 ❤️➕💯 Jessica's message. 

Gryphon, Your technically correct grammar facts are so vastly outweighed by what makes most sense for a quizzer to hear. 😉

**Comment by scottpeterson** [comment]
I will die on this very small hill.

**Comment by kclimenhaga** [comment]
I dispute Gryphon's assertion that "multiple answer" is an adjective. In the quizzing context, these questions are "chapter (verse) reference, sub-type multiple answer". No adjectives involved except "multiple", which modifies "answer" rather than "chapter reference". 

Language nerd aside, I agree completely with Jessica's statement. I always announce these questions as CRMA/CVRMA, and I think they should be worded that way in the rulebook.

**Comment by jswingle** [comment]
+1 because of the type/sub-type argument mostly. I'm not quite so much a language nerd ;-)

**Comment by jttower** [comment]
Rules Committee voted 3/20/22 to make the change to CVRMA/CRMA in the rule book to make it consistent throughout, whether abbreviated or spelled out.  
Vote passed 6-0.
On behalf of the Rules Committee, this issue is closed.
