### ISSUE TITLE
Rule 3.6 Jumping - eliminate prohibition against forfeiting a question

### ISSUE THREAD

**Issue by JoshJetto** [gryphonshafer/Quizzing-Rule-Book#128]
I am proposing that we strike the following from the rulebook under this rule heading:
"If in the judgment of the officials, a deliberate attempt is made to forfeit a question, an error will be charged, and 10 points deducted from the team score. The next question will be the same number."

I think we should eliminate this rule that makes it illegal to "intentionally err" on a question. There are some situations (as you all know) in which it is strategically the correct move to jump as fast as possible not because you are trying to get an error, but because you cannot lose if you get the jump - whether you answer correctly or incorrectly. The current situation requires officials to police the internal motivations of the quizzers and the quizzers (who know about this rule) to police their own motivations in such strategic situations, and they are restrained by the current rule from actually doing what is best. In fact, under our current rules, when a team that is ahead by 30 points on question 20A gets the jump and errs, the team that is 30 points behind could legitimately challenge that the other team committed a rules violation, should lose 10 points, and the question should be redone. 

I am not opposed to changing the language of this rule to reflect only the situation in which a team may be intentionally burning specialty questions by over-jumping the questions to prevent a specialist from another team from having a chance at them. That, in my opinion, is mean-spirited and poor sportsmanship. If we did make this change, then the erring team should be charged an error, penalized 10 points, and the question that is redone should be of the **exact same type**. However, the rule as currently written prevents a team from legally doing what is strategically correct (and not in a mean-spirited way) in order to win at the end of the quiz, and it also allows the team that is behind to legally and legitimately challenge any error the leading team makes on an "A" question that makes winning impossible for the trailing team. Not only that, the rule as currently written - by allowing such a challenge - would create a situation in which the leading team, having been charged with an error on 20A, would have to sit out as 20A is redone as a toss-up with only one team eligible to jump - the trailing team. This all but assures that the trailing team will be able to win through a 3rd or 4th person bonus, since 20A is not a bonus question, and the leading team, after being charged with an error, would now only be 20 points ahead.

**Comment by jswingle** [comment]
I agree it's tough to ask officials to "police the inner motivations" of the quizzers. I did invoke this rule one time as an answer judge at Internationals, the specifics of which are a bit complex to relay here.

I don't think it's a _good_ thing that the leading team on 20A can swipe a 3rd person bonus from the team that's behind, but I also don't know that this rule can stop it in most circumstances. I think the best option would be getting rid of it in favor of changing the scoring structure to reduce instances where the quizzers are motivated to "throw" a question to begin with. 

It might be hard to get rid of every "mismatched incentive" so long as we have a 3-team competitive structure and we allow multiple teams from the same church/district, but we can at least try to change rules to fix the most obvious loopholes like this one you've described.

**Comment by ARMediting** [comment]
This is another of those "you know it when you see it" types of rules—which is by no means bad. And it is incredibly rare for anyone to invoke. One of those "we're all cheating so let's not talk about it" scenarios that would have to be _very_ blatant to invoke, and even harder for an accusing team to convince the officials of.

Also, I've never noticed this before, but is this the only scenario in which an error is applied to a question that is then redone? ("The next question will be the same number" does not accurately describe what's happening. It's being thrown out.) Also, as it's worded, wouldn't it allow for a potential total of 20 points to be deducted from one team? 

Furthermore, if it happens on, say, question 10, then the team caught forfeiting loses points, sits out, and question 10 is reread. If both other teams error on 10 and 11, what happens on question 12?

What if the penalty was a foul on the quizzer who jumped, and that team sits out while the question is thrown out and redone? There's still a potential for a loss of points, but only if it's the fourth or more team foul. We'd also have to specify if the team sits out for the numbered question or more or less.

**Comment by jswingle** [comment]
Yes @ARMediting you're right about that. The procedure for what to do here is very weird and can result in lots of negative points, a loophole which was exploited endlessly by a bunch of PNW quizzers in a long van ride when we were attempting to figure out the lowest possible score in a quiz. You re-do the exact same question number, but with a negative penalty. The rules aren't extremely clear about it, but it seems most likely that "an error will be charged" means the offending team is sitting out the re-done question, and the question becomes like a toss-up or a bonus.

When I invoked the rule as an AJ, it was such a rare occurrence that we called in the meet director before making the decision. Even though the issue spanned multiple questions, we decided to just re-do Q20 with the offending team sitting it out, as described in the rulebook.

**Comment by jswingle** [comment]
Coming back to this issue @JoshJetto --

I think we should consider removing this rule as you're recommending, but I also think such a change should be accompanied by a reconsideration of the features of the scoring system which lead to circumstances in which it can be to a quizzer's advantage to "forfeit" a question to begin with. This is a complex question. Here is one scenario already mentioned in which it can be to a team's advantage to "forfeit" a question:

`Toss-up on question 20A between two teams who are 30 points apart. There are quizzers on the team that's behind who can jump and get a 3rd person bonus to tie it up. If the team that's ahead wins the jump, then they win no matter what, so the natural competitive incentive is for them to do whatever they can to win the jump. `

In the above scenario, we shouldn't attempt to read the minds of the quizzers and penalize them for doing _what the competitive structure incentivizes them to do._ We should instead change what the competitive structure incentivizes.

Can anyone think of any other examples, however rare, where the current scoring rules can incentivize forfeiting questions?

**Comment by jswingle** [comment]
^I can think of Band-Aid fixes of varying quality to the specific problem above, such as:

- Bonuses are worth 20 points even at the end of a quiz
- 3/4/5th person bonuses can be awarded on bonus questions
- Make some specific rule targeting this situation exactly, such as an error on 20A giving a team that's ahead a 20 point subtraction instead of 10

I think it will be less difficult to figure out _fixes_ for these bad incentives, than it will be to _identify_ all such bad incentives in the first place... I am quite sure there are more possible scenarios than this one.

**Comment by ARMediting** [comment]
Those first two suggestions would significantly shift team strategy in situations unrelated to the one we're concerned about. I'd rather make a small tweak to the situation we're concerned about.

**Comment by JoshJetto** [comment]
I don't think the scoring rules are bad, and if a team has gotten themselves into an advantageous scoring position on question 20a, they should be rewarded for that not penalized. Similarly, if a team is behind by 30 on question 20, then it's on them to get the jump on question 20 to get the 3rd, 4th, or 5th person bonus, so it doesn't go to 20a. They should not be "gifted" the opportunity in that situation to sit back in hopes that the leading team will err on 20 and put them into a winning situation on 20a. If we want to keep the rule to avoid the unsportsmanlike burning of questions (like knowing someone is a quote person on another team and purposely burning the quote questions to prevent them from getting right answers early in the quiz or where it's clear that one team is seeking to benefit another for reasons of favoritism), then we should specify that in the current rule and state that it does not apply to end of quiz situations where the score dictates that this is the best strategy.

**Comment by scottpeterson** [comment]
100000000% agree.    If intentionally sitting is the optimal strategy, it should be allowed. It intentionally erring is the optimal strategy, it should be allowed. 

This is why I'm also fine with a team in finals, who will lose a quiz, helping one of the other 2 teams win the quiz, so the other team doesn't get their 2nd win. 

I'm less fine with it when it's one church/district helping a team from the same church/district, when the only reason they're helping is because the other team is from the same church/district.

**Comment by scottpeterson** [comment]
Not sure if you were taking a stance on this specific point Josh, but I'm personally fine with a team intentionally burning a question to thwart another team's specialist.  If someone is both that good at a single question type and that bad at all other types that this is a beneficial strategy for other team's to take, that's on you for limiting your prep.

**Comment by jswingle** [comment]
I don't have a problem with a scoring ruleset that can incentivize "intentionally sitting," but I don't want to incentivize "intentionally erring."

To clarify and make a distinction: I think it is totally fine if quizzers occasionally have the incentive to jump _very aggressively_ on a question to deny another team a specialty question, such that their likelihood of getting it correct is lower than they might prefer - but they're still going to _try to get it right_. This is a normal and exciting part of quizzing strategy.

I think this is a different category than a ruleset which makes it _more or less irrelevant whether or not the quizzer even tries to get 20A right._ In elimination rounds, it is immaterial if the team that's up 30 on 20A even gets the question right or not. (Even for individual points, which are usually not scored in top 9.)

Normally I try to come up with objective criteria when I talk about rules, but honestly my best argument for this is that I think it's _lame._ I don't think it is necessarily "unfair" to the team that is down 30 - @JoshJetto is correct when he says " it's on them to get the jump on question 20 to get the 3rd, 4th, or 5th person bonus." My concern is not that the current ruleset is unfair, but that it incentivizes a strategy that is anti-competitive and not fun.

**Comment by JoshJetto** [comment]
I'm just coming back to this issue to point out that should we remove this rule according to my initial proposal that we would also need to strike the sentence that relates to it in 6.1.3. Points Deducted, which states: "-10 points at the determination of the room officials that a deliberate attempt was made to forfeit a question." I am very strongly in favor of this. 

Also, to Jeremy's point that it incentivizes a strategy that is anti-competitive and not fun, I disagree. This is one of those somewhat unique competitive strategy situations that is fun to employ, and also for the team in the behind position to catch the team that could have thwarted their tie or victory by being more situationally alert on 20A or on 19A in certain situations (such as when you can block a team from even being able to achieve a 3rd Person Bonus by burning 19A when up by 40 and only one quizzer has answered a jumping question correctly from the other team).

**Comment by ARMediting** [comment]
I'm with Jeremy in thinking it'd be depressing and discouraging to watch a team burn a question (especially 18 or 19) and obviously not even try to get it right. I'm also a bit confused why the current rule about it is under "Jumping" instead of "Fouls."

I'd be okay with removing the language from 4.6 [3.6] and 6.1.3., if we could add a bullet point in 5.5. to the effect of "An obvious deliberate attempt to forfeit a question." This would remove confusion from questions of deductions and rereadings of questions and lower the penalty to an individual foul. Plus, "obvious deliberate" limits the consideration to bad-faith behavior like not trying to answer the question at all or burning a specialty.

Or, what about a tweak to the first sentence of 5.5.: _A foul is a penalty called by a quiz official against a quizzer or team for conduct that breaks the text or spirit of the rules **or of competition**._ That would still give officials leeway to call fouls based on poor sportsmanship, if an attempt to burn a question feels like it's crossed into that territory.

**Comment by 24RMiller** [comment]
The Introduction of the Bible Quizzing Rule Book defines Bible Quizzing as: "a Christian sport in which teams of participants compete on Bible memorization in a context that requires a combination of speed, accuracy, and strategy and a culture that inspires collaboration, fellowship, and mutual encouragement." I see nothing in here that opposes intentionally erring a question. If anything, an intentional error is part of the strategy mentioned above. Thus, I agree we should remove the rule mentioned above.

Here's the problem I find with this rule: As others have alluded to, it can be extremely hard to judge whether a question was forfeited intentionally. For example, if the team is up 30 points going into Question 20a, it makes it difficult for them to jump. They know that an error wins them the quiz, so their coach tells them, "As long as you get the jump you win." Thus, they agree to jump on the first syllable. In this scenario, they are not necessarily intentionally erring, but assuring they obtain the jump. They could easily jump on a unique word on that first syllable and answer correctly. On the other hand, they could jump on "What..." In the second case, it could be interpreted that the question was erred on purpose. However, the intention was not to "forfeit the question", but to prevent this other team from obtaining the jump. 

This rule seems unnecessary and allows for more subjectivity. The scenario when a question is forfeited on purpose seems extremely rare. This rule potentially puts the team ahead by 30 points going into 20a as a disadvantage. They might slow down because they're worried it will be considered an intentional error, while the team behind has nothing to lose, knowing this rule does not apply to them. Additionally, in this scenario, the score between the two teams involved in the toss-up would almost certainly be the same heading into 20 and 20a (barring a 2nd overruled challenge or foul out), so no matter what, the team behind should have a fair shot at Question 20 (The only potential issue I see is if the score is something like 140,130,100, so the team with 100 is forced to sit out 20 for strategic reasons. However, in this scenario, if the team with 140 erred, it would make no sense for the team with 130 to intentionally forfeit 20a.). As a result, this rule should be removed because it takes away some of the strategy quizzing necessitates.

**Comment by ARMediting** [comment]
On behalf of the Rules Committee:

During the 6/11/2023 meeting, the committee voted 6-0 to delete:

- the last bullet point in 4.6. Jumping: "If in the judgment of the officials, a deliberate attempt is made to forfeit a question, an error will be charged, and 10 points deducted from the team score. The next question will be the same question number."
- the fifth bullet point in 6.1.3. Points Deducted: "-10 points at the determination of the room officials that a deliberate attempt was made to forfeit a question";

and to add a bullet point to 5.5. Fouls: 

- “Unsportsmanlike conduct as determined by the quiz officials”

For more information on the rulebook Change Management Process, please visit: https://github.com/gryphonshafer/Quizzing-Rule-Book/blob/master/content/rule_book/change_management.md
