### ISSUE TITLE
Quiz Events | Answering a Question Procedure 

### ISSUE THREAD

**Issue by ZacharyTinker** [gryphonshafer/Quizzing-Rule-Book#146]
In many districts, there is an idea that the quizzer must stand in order to answer the question. While this is not outlined in the rule book specifically it is a near-universal unwritten rule. 

Another unwritten rule that is used in many districts is that if a quizzer sits down after standing, they give up and don't want to keep guessing at an answer. Right now, there is no official way for a quizzer to forfeit the remainder of their time. 

I would propose that the following rules be added to the Quiz Events section of the Rule Book. 

- A quizzer has 30 seconds to give the correct answer (present in 4.1 of the current Rule Book)
- A quizzer must stand in order to give an answer
- If a quizzer takes a seat back on their bench during the 30 seconds, the quizzer forfeits the remainder of their time, and the ruling will be given by the officials. 

*If the quizzer is using a hand buzzer the second two rules would not apply. A variation could be created. 
_________________________

Now onto why I think this would be a net positive change for both quizzing in general and for the quizzers most importantly. 

By having the quizzer stand, it does two things. Confirms that the quizzer is recognized by the quiz master and they acknowledge the recognition. (See 4.5 fouls) 

This also makes it easier for the Quiz Master to hear the quizzer as they give an answer. 

It is completely demoralizing to jump on accident and not have any idea as to how to answer or to think you knew the answer, jump and then blank. Being allowed to forfeit the remaining time would allow the awkward feeling for the quizzer of having to stand and stare for 30 seconds to be removed. (I've personally been there as a quizzer in the past.) While this happens less at IBQ, in districts this is a much more common occurrence. e.g. Rookie falls off the bench and hears absolutely nothing the QM said while reading the question. (Again, I've personally been there as a quizzer). 

If implemented a non-verbal signal is the only way to do it, as nothing would demotivate like having to say, "I give up."

I believe these two rules combined would create a more positive situation for all involved.

**Comment by JoshJetto** [comment]
I like this.

**Comment by jttower** [comment]
I am also in favor of this.

**Comment by jswingle** [comment]
I like the idea as well, but I would add that if we require standing to give an answer, the rules should not consider it a "foul" if the quizzer stays on their chair and starts giving an answer. The quizmaster should simply prompt the quizzer to stand.

**Comment by jonathanvanschenck** [comment]
I am in total agreement about codifying "sitting back down" as the method of forfeiting ones remaining time.

However, I am pretty opposed to adding the requirement to stand. As proposed, I think it leaves too many cases unanswered, but more broadly I think requiring standing is needless arbitrary.

For instance, as Jeremy said, we would need to add some additional prompt phrase that QMs could use to ask a quizzer to stand.

But, what about rooms that have microphones in them? Should quizzers also be required to approach the microphone? From a consistency standpoint I think we would have too, but trying to implement and enforce that rule would be an absolute nightmare.

While the standing rule would (likely) result in clearer answering by some quizzers -- it is by no means a universal guarantee. Plenty of quizzers just has soft voices, or will just mumble irrespective of posture. I don't have any data on this, but my suspicion is that the majority of unclear answers are not caused by partial standing, but by other things like anxiety or quite disposition.

Also, while there is the theoretical benefit of have the quiz acknowledge being acknowledged -- I don't think there would be any functional utility. The vast majority of quizzers acknowledgements are unambiguous, and I just don't see a standing requirement as actually helping in the few edge cases.

It seems to me that the standing rule is really more of an etiquette concern than something which is actually necessary for clean and consistent quizzing. There are plenty of etiquette issues that shouldn't be rules, and I think this of over of those.

**Comment by jonathanvanschenck** [comment]
Okay, I actually have a counter proposal -- the best practices document should have a Quizzers section added, and *that* should include things like:

- quizzers should stand to full stature before beginning their answer

**Comment by ARMediting** [comment]
I like the suggestion to add this to a best practices situation. Would it be worth bringing back the "Quizmaster Should" section of the rulebook for things like this? If there's no penalty to the quizzer for not doing it, then it's not worth challenging, right? Similarly, we could add "The quizzer should" stand and/or speak loudly enough to be heard.

**Comment by scottpeterson** [comment]
I'm in favor that for a quizzer who has stood up, that sitting down equates the end of their answering.

I'm less in favor of requiring a quizzer to stand up. Then you invite situations of a quizzer starting to answer while in the process of standing up and the QM needing to decide when to "start considering the quizzer's response as grounds for a ruling."

Now, that means that a quizzer who answers sitting down, has no recourse to signal that they are done answering by sitting down, but I think that's fine. 

I am strongly against adding a QM prompt for the quizzer to stand. It's another thing for the QM to have to do (and potentially have to do in a timely manner lest invite a challenge). Quizzers should know what gives them the best chance at being counted correct. We don't currently require QM prompts to "speak up" or "speak more clearly" or anything of that nature.

**Comment by jswingle** [comment]
I think that's reasonable and probably the best way to go about it.

**Comment by ARMediting** [comment]
I'm in favor of adding a statement to the effect of "If a quizzer who has stood to answer sits back down on their seat, the quizmaster shall take this as the quizzer forfeiting the rest of their time."

Where to add it? 4.1., Answer Duration? 3.5., Platform Protocol?

**Comment by scottpeterson** [comment]
Good question. Probably Answer Duration?

**Comment by jswingle** [comment]
I like @ARMediting 's wording. I like that it specifies "has stood to answer" so that it doesn't put push-button quizzers in a weird spot. I agree with Scott that it goes best under 4.1 Answer Duration, since it is a means by which a quizzer can reduce their answer duration.

I would recommend an edit for precision: "If a quizzer who has stood to answer sits back down on their seat _during the answering period,  they forfeit the remainder of their time_."

**Comment by levikoral** [comment]
I also agree with @ARMediting and his wording sounds fine.

**Comment by jttower** [comment]
I like this wording as well:
"If a quizzer who has stood to answer sits back down on their seat during the answering period, they forfeit the remainder of their time."

**Comment by JoshJetto** [comment]
The Rulebook Committee voted 5-0 to add the following to this section of the rulebook: "If a quizzer who has stood to answer sits back down on their seat during the answering period, they forfeit the remainder of their time."
