### ISSUE TITLE
Reduce Usage of XYZs

### ISSUE THREAD

**Issue by ARMediting** [gryphonshafer/Quizzing-Rule-Book#162]
The only current limiting of the use of XYZ quizzes currently in the rulebook is when nine teams or fewer are in a tournament. However, with the high number of prelims taking place in the past few decades, XYZs are redundant. Team performances will have averaged out across the 10+ prelims, and there's less concern of getting a bad draw. 

I don't know anyone who likes being in an XYZ, even if they have a chance to move up in position. It's stressful after prelims, the resulting shuffle doesn't usually benefit many teams, and it increases the chance of one bad quiz significantly lowering the spirits of a team right before a break. I see a few possible changes:

- Eliminate XYZs entirely.
- Only require XYZs if a tournament has 6 (or 8, or whatever we decide, or depending on the number of teams) prelims or fewer.
- Only require XYZs if teams 7-15 are separated by fewer than a certain number of computer points.

It would be nice to keep the format somewhere in the rules or alternative rules so people running smaller tournaments can use it if they feel the need, but do we ever see IBQ returning to a low number of prelims?

**Comment by josiah-leinbach** [comment]
If we are going to do anything with regard to XYZs, I would favor striking them from the rulebook entirely. They do not really serve a purpose even in a tournament with few preliminaries, since in that case they function just as an additional prelim quiz.

I get the point for why XYZs exist, and in theory it's a good one. However, I do not think they hold up empirically. If (and that is a big if) any shifts take place, it's usually 9th and 10th flipping spots, or maybe 11th getting in there if things are very tight. But if things are that tight going into XYZs in a high prelims tournament, they were likely close in the final few prelim quizzes anyway, in which case coaches should be aware of that and strategize accordingly. 

I could be persuaded that a point-spread trigger is doable, but that would be mostly arbitrary and give rise to problems. For example, suppose we set the point-spread trigger at 10 points between 7th and 15th. Now suppose that after prelims 9th and 10th are separated by 1 point but 7th and 15th are separated by 11 points. That would probably not be known until after the quizzing is done, but now 10th place gets locked out of the championship bracket because of how 15th place quizzed, when 10th could have strategized differently. Not knowing whether XYZs will happen just seems like a liability that allows other team's performances to influence outcomes for team's that they are not directly quizzing against.

Thus, I stand by my suggestion to strike them entirely.

**Comment by jswingle** [comment]
I'm partial to the idea of defining the tournament format in a separate document from the rulebook itself. I feel like the tournament format should be subject to change depending on # of participants (as was the case in 2022 IBQ).

But regardless of that, I agree that XYZs are unnecessary in _any_ format. If we want to still explain their use somewhere, it should be outside the rulebook.

**Comment by ARMediting** [comment]
The Rules Committee voted 5-0 on Jan. 7, 2023, to delete the wording in 7.2. regarding XYZ quizzes and revise some of the language around tie-breaker criteria:

New:
> 
> 7.2. Elimination Rounds
> 
> The following may be used, in order, to break ties in team placements after preliminary quizzing:
> 
> Head-to-head competition in previous quizzes
> Total points scored in preliminaries
> Least number of errors
> 
> In addition, a tie-breaker quiz may be used for ties that determine which bracket a team will compete in for elimination quizzing.
> 
To be removed: 

> When more than 9 teams are involved, at the determination of the meet director and announced before the meet begins, there may be XYZ quizzes following these guidelines:
> 
> 	If there are 10 to 14 teams, the top 9 should be placed into a final 9 championship bracket after the opening round, for the elimination round, and the remaining teams dropped.
> 	If there are 15 to 20 teams, the top 6 teams should be placed in the championship bracket, the next 9 places (7 through 15) should quiz in the intermediate quizzes given below (XYZ) and the remaining teams should be dropped.
> 	If there are more than 24 teams, the top 6 should be placed in the championship bracket, teams 7-15 should quiz in the XYZ quizzes to determine places 7-15. Teams 16-24 will quiz in XXYYZZ intermediate quizzes given below to determine their placement.
> 
> A Consolation Final 9 bracket will be used for positions 10-15 (determined by XYZ quizzes) and places 16-18 determined by XXYYZZ quizzes. The teams in the XYZ quizzes cannot move below position 15, regardless of how low their XYZ quiz score was. Likewise, the teams in the XXYYZZ quizzes cannot move above position 16, regardless of how high their intermediate quiz scores were.
> 
> XYZ Quizzes
> 
> 	Quiz X: Teams 7, 12, 15
> 	Quiz Y: Teams 8, 11, 14
> 	Quiz Z: Teams 9, 10, 13
> 
> XXYYZZ Quizzes
> 
> 	Quiz XX: Teams 16, 21, 24
> 	Quiz YY: Teams 17, 20, 23
> 	Quiz ZZ: Teams 18, 19, 22
> 
> There will be a tie-breaker quiz for positions 6, 15, and 24. Ties for positions 7 through 14 will be broken in accordance with the following priorities:
> 
> Points earned in these quizzes should be added to the points earned in the opening round by each team. The highest 3 teams, based on the point system above, are then placed in the above bracket. The next 6 teams are placed in the lower bracket.
