### ISSUE TITLE
QM prompt timing for pronouns clarification

### ISSUE THREAD

**Issue by scottpeterson** [gryphonshafer/Quizzing-Rule-Book#30]
Currently the QM must prompt for pronoun clarifications when the quizzer has completed all answer text. This seems odd, since the amount of question text the quizzer may have to respond with varies based off jump speed. Much like ref questions, seems like the QM should be consistent, and wait for all text in question and answer to be given before prompting for pronoun clarification.

**Comment by jswingle** [comment]
I agree completely, but there's something interesting I found when reading the whole rule:

```
2.2.1.1.1 Pronoun Clarification

If a quizzer has provided all the information in the answer, except the identification of a pronoun present which is part of the answer text, the quizmaster will ask the quizzer to identify the specific pronoun. For example: "Can you identify 'He'?" or "Can you identify 'They'?"

The quizmaster is not allowed to say anything other than what the quizzer has already said when asking for the identification. A pronoun may need to be identified only if the antecedent is in context.

Once the quizzer has provided all information in the question and answer, the quizmaster will prompt the quizzer to identify the specific pronoun.
```

Look at that last paragraph. That one contradicts the first paragraph by also including the "question" part! My guess is that this is just a straightforward rulebook bug of imprecise language, and the intent of the rules all along was to function exactly as you propose.

My proposed solution? Just get rid of the last paragraph of this section. It's 100% redundant with the first paragraph. And then edit the first paragraph to say (changes in italics):

`If a quizzer has provided all the information in _the question and_ answer, except the identification of a pronoun present which is part of the answer text, the quizmaster will _prompt_ the quizzer to identify the specific pronoun.`

**Comment by JoshJetto** [comment]
I agree with Jeremy's change.
Separately, not to a throw a wrench into things here, would there ever be a pre-jump situation in which the quizzer has substituted a pronoun for a specific noun in the question (or God/Lord for a specified Person of the Trinity), where the quizzer clarifying the specific noun in the question text would be necessary for them to be called correct? If so, then should we have a rule about quizmasters prompting a quizzer to clarify the pronoun in the question text if that is what is needed for the quizzer to be called correct?

**Comment by jttower** [comment]
To deal with Josh's scenario, we could just change it to:
"If a quizzer has provided all the information in the question and answer, except the identification of a pronoun present, the quizmaster will prompt the quizzer to identify the specific pronoun..."
Then it applies to any pronouns used, not just in the answer.

**Comment by JoshJetto** [comment]
This change wouldn't fix the issue, since a quizzer is not required to identify pronouns that are in the question as written (and shouldn't have to). The situation I brought up has to do with a quizzer omitting a specific noun that is in the question by substituting a pronoun for it when the quizmaster judges that the specific noun is an essential part of the information in the question that is needed to call the quizzer correct.

**Comment by jttower** [comment]
@JoshJetto , I see what you are saying.  How about this:
"If a quizzer has provided all the information in the question and answer except the identification of a pronoun that is necessary information, the quizmaster will prompt the quizzer to identify the specific pronoun..."
(I took out an unnecessary comma as well.)

**Comment by jswingle** [comment]
This exact issue has come up in some very weird corner-case rulings before, but unfortunately I can't remember the scenarios. A QM asked for a pronoun clarification where there wasn't one in the text, and the question ended up being redone after a challenge.

I would strongly push that we only allow the QM to prompt clarification for a pronoun that is actually _in_ the text. If a quizzer says a pronoun where there's not one, that should be an "Again" prompt.

3 arguments for this:

(1) The point of asking clarifications is not to "help" the quizzer figure it out when they quote incorrectly, it's to let them know that they _did_ quote it correctly but we want more information from the context - information that would otherwise be unreasonable to expect the quizzer to realize we need.

(2) This would be very difficult to maintain consistency across rooms/QMs, or even with the same QM across time. Pronouns are a broad grammatical category, and QMs should not be expected to know off the top of their head that things like "when" "each other" or "something" can all be pronouns. We're asking the QM to decide quickly on the fly whenever _anything_ in the answer text is replaced with a pronoun.

(3) From a spirit of quizzing standpoint, I don't think the officials should take any actions which may indicate the text is anything other than exactly what it is. This may sound nitpicky, but I do think there is value to keeping the pronoun clarifications from becoming "sloppy" in any way.

**Comment by ARMediting** [comment]
Totally agree with Jeremy. I've seen the situations he describes, and I would love to write them out of being a possibility.

**Comment by jswingle** [comment]
On behalf of the Rules Committee:

During our meeting on 03/20/2022, the Rules Committee voted 6-0 to approve the change detailed below. This means that a "pull request" has been made - in other words, a change has been officially proposed and voted on by the Rules Committee, and will be given a final vote in 3 months. For the next 3 months, please view and comment on the pull request by following this link: https://github.com/gryphonshafer/Quizzing-Rule-Book/pull/141/files

The text has been changed to read: "If a quizzer has provided all the information in the **question and** answer, except the identification of a pronoun present which is part of the answer text, the quizmaster will **prompt** the quizzer to identify the specific pronoun..."

The following has been deleted entirely: "Once the quizzer has provided all information in the question and answer, the quizmaster will prompt the quizzer to identify the specific pronoun."

Since these two sentences were repetitious but had a small contradiction, we deleted one of them and went with our preferred route: that all information pertaining to a question must be given before a pronoun prompt occurs, regardless of whether the information is in the question or the answer.

For more information on the rulebook Change Management Process, please visit: https://github.com/gryphonshafer/Quizzing-Rule-Book/blob/master/content/rule_book/change_management.md

For the minutes of this particular meeting, please visit: https://docs.google.com/document/d/1jDIGi5LmVHbVWUmAK0-6EhJjATlI9398zK-V8Be2zNE/
