### ISSUE TITLE
Substitutions

### ISSUE THREAD

**Issue by scottpeterson** [gryphonshafer/Quizzing-Rule-Book#36]
Remove the sit out for 3 questions limit (would necessitate 1 sub per TO).
Remove the "quizzed out quizzer can't come back into a quiz"

These clutter up officials job. And should not be attempting to mandate coach behavior, under the guise of assuming the rulebook writers know what "good" is.

**Comment by jttower** [comment]
I agree with @scottpeterson that I think these rules could be removed.  I feel strongly about the second one, that quizzed out quizzers should be allowed back on the platform even if they've been subbed out.  What if they were subbed out in order to let the 5th quizzer in, but then a different quizzer errs-out?  The quizzed out quizzer should be allowed to return to the platform because they should be eligible to jump on bonus questions.  I feel less strongly about sitting out a minimum of 3 questions, but I don't see a strong reason to keep it in the rules.  If a coach wants to burn a time-out to put someone back in 2 questions later, I don't see the problem with that.

**Comment by JoshJetto** [comment]
I agree with both of these proposals as well. I think it is imperative that we remove the prohibition against bringing a quizzed out quizzer back on the platform for any reason. The coach should be allowed to sub them back in, since they are eligible to jump on bonus questions. I am also in favor of eliminating the three question waiting period for a quizzer that has been subbed out. I don't see any real rationale necessitating this being a rule and removing it would be a positive simplification of the rulebook.

**Comment by jttower** [comment]
On 6/11/23 the Rules Committee voted to strike these three sections from 5.7 Substitutions: 

- A quizzer being removed from a quiz must stay out for a minimum of 3 question numbers, including alphanumeric question numbers, before re-entering the quiz
-  If subbed-out, they may not return for any reason
- even if the incoming quizzer has been subbed-out less than 3 questions ago.

----

So the new wording in section 5.7 Substitutions is as follows: 

Substitutions may be made only during timeouts or to replace a quizzer who quizzes-out, errs-out, or fouls-out on the immediately preceding question.

- A team can only make 1 substitution per timeout.

- Quizzers can be substituted for any chair.

Quizzed-out quizzers may remain in the quiz to answer bonus questions. Substituting for them afterward will require a timeout. 

When a quizzer quizzes-out, errs-out, or fouls-out and leaves the platform after the event, a substitute may take their place immediately and without a timeout.
