### ISSUE TITLE
QM explanation of a ruling

### ISSUE THREAD

**Issue by scottpeterson** [gryphonshafer/Quizzing-Rule-Book#43]
"No comment other than "correct" or "incorrect" need be announced by the quiz officials in making a decision."

while it's not a good idea to require a certain amount of explanatory language of a ruling, it should absolutely be a best practice, especially when the ruling was tough, or in a judgmental gray area. QMs should not intentionally hide behind tough rulings by giving the bare minimum "correct/incorrect."

**Comment by kclimenhaga** [comment]
Agreed. I think, for example, that the quizmaster should generally provide the correct answer if a quizzer has been ruled incorrect. Certainly, if the quizmaster does provide the correct answer, I do not think this should prevent a challenge.

**Comment by scottpeterson** [comment]
Agreed on both points. The ONLY thing that would give me pause on REQUIRING the QM to state the entire correct answer is F2V/Q2V. 

THOUGH, if hypothetically the written answer has a word incorrect, that shouldn't be grounds for challenge, sooo, I'm second-guessing myself a small bit now.

**Comment by kclimenhaga** [comment]
I would never require QMs to state the entire correct answer on any Finish/Quote. My practice is usually to state the part the quizzer got wrong, or to give the start of the quote if they had the wrong verse.

I'm not sure what you mean by the written answer having a word incorrect. If the quizmaster rules an answer to be incorrect because of something incorrect on the written question, it should be challenged, should it not?

**Comment by scottpeterson** [comment]
If the question was "For God so loved what?" and the written answer was "a world", a quizzer shouldn't be able to challenge and get the entire question thrown out because the answer was mistyped.

**Comment by scottpeterson** [comment]
It's a similar scenario to say a 9-word Interrogative question, where word 8 was wrong, but the quizzer jumped before then. The fact that the written question had a textual error that was immaterial to what happened shouldn't be grounds for having the question thrown out.

**Comment by kclimenhaga** [comment]
I agree, but if the quizzer had said "the world" and was ruled incorrect because the quizmaster was expecting "a world", that should be challenged.

If the quizzer had been called incorrect because they had said "the heavens" instead, then I agree that this should not be challenged, but challenges are against rulings, not question wordings, so I'm not sure what a quizzer would say in a challenge in the first place.

**Comment by scottpeterson** [comment]
Totally. If the typo (or flat out incorrect) question or answer text factored into the ruling, should be able to be challenged (and SHOULD be caught by the table and thrown out, even before a challenge). 

I mean, if I was a quizzer and the QM read the correct answer and it was a word off, I'd totally take a shot at challenging to get the question thrown out because "it's not a valid question. The question+answer text on your card doesn't exist in the material" (and deliberately not draw attention to the fact that it had no impact on me getting it incorrect )  ;-)

**Comment by scottpeterson** [comment]
And I should clarify, a quizzer is allowed to challenge most anything.  An immaterial typo in the written answer should result in the challenge being overruled.

**Comment by jttower** [comment]
We could add a sentence to the effect of " the quizmaster should generally provide the correct answer if a quizzer has been ruled incorrect."  If you think it should also say "on a Q/F question, the quizmaster may provide a section of the verse" we can also do that.  Suggestions?

**Comment by ARMediting** [comment]
[Purely commentary below, I'm torn on the issue]

I've seen a lot of challenges rise and fall on the basis of what a quizzer _thought_ the question and answer were. If a quizmaster is known for giving some explanation and then doesn't give any, correct or incorrect, it can be a clue that they anticipate a challenge (and a clue to a captain that they should be making a challenge—a sharp captain can take advantage of this!).

How many challenges could we save quizzers from needing to make if we explained or read out more questions? How much would these explanations or full readings, if standardized (even if they didn't include finish and quote types), bog down the pace of a quiz?

**Comment by jswingle** [comment]
I think it's a gray area and highly individual to a quizmaster's style and preferences. I always give detailed explanations if I think there's any chance of a challenge, simply because I've been around the block a while and 90% of the time I already know what the quizzer's challenge is going to be about and already considered it before making the ruling. I figure it saves time and avoids quizzers getting too many overthrown challenges if they already know my thought process and are able to consider what I'm considering before making the choice to challenge.

At any rate, this is definitely a best-practices item, not the main rulebook. It should be considered standard practice for the QM to give the correct answer, or at least the start of the verse or next few words in a QT/FTV/SIT quotation, but I don't think a QM failing to do this should ever be grounds for a challenge/protest, it should just be brought to the attention of the QM by a coach/quizzer/spectator who can point to the best practice.

**Comment by jttower** [comment]
On 6/11/23 the Rules Committee approved the following insertions and deletions from 3.2 under Quiz Officials:

INSERT: _If a quizmaster calls a quizzer correct, no explanation of the ruling is needed, though the quizmaster or answer judge may provide an explanation at their discretion. If a quizmaster calls a quizzer incorrect, the quizmaster or answer judge will provide a brief explanation of the ruling._

DELETE: (No comment other than "correct" or "incorrect" need be announced by the quiz officials when announcing a ruling; however, at the discretion of the quizmaster (QM) and answer judge (AJ), or at the request of the captain, additional information may be given.)

DELETE: (If the additional information regarding the ruling is provided at the discretion of the QM/AJ and not at the request of the captain, this is not considered an explanation of a ruling, which would invalidate a challenge or protest.)

LEAVE AS IS: If the captain requests additional information regarding the ruling, this is considered an explanation of a ruling and invalidates a challenge or protest. Before replying to a request for an explanation, the QM must ask all teams if they wish to challenge.

LEAVE AS IS: All conferring between quizmaster and answer judge(s) shall be done privately.


---


So the section under 3.2 Quiz Officials will read:
If a quizmaster calls a quizzer correct, no explanation of the ruling is needed, though the quizmaster or answer judge may provide an explanation at their discretion. If a quizmaster calls a quizzer incorrect, the quizmaster or answer judge will provide a brief explanation of the ruling.

If the captain requests additional information regarding the ruling, this is considered an explanation of a ruling and invalidates a challenge or protest. Before replying to a request for an explanation, the QM must ask all teams if they wish to challenge.

All conferring between quizmaster and answer judge(s) shall be done privately.
