### ISSUE TITLE
Revisit italic terms ideas

### ISSUE THREAD

**Issue by gryphonshafer** [gryphonshafer/Quizzing-Rule-Book#54]
For v1, during manual paper review, it became clear that identifying defined terms with *italics* was a visually distracting practice. So for v1, I've removed all *italics*.

For v2, it might be useful to consider or at least debate some other way to visually identify terms that are defined somewhere else in the document. **Bold** would likely be too much just like *italics* is. But we might be able to brainstorm a clever idea.

**Comment by jswingle** [comment]
To clarify @gryphonshafer when you talk about terms that are defined somewhere else, do you mean terms that appear in the Definitions section, or just any term that has a specialized use throughout the rulebook? Should there be an alphabetical glossary of terms which we bold (or otherwise indicate) at the end of the rulebook?

**Comment by gryphonshafer** [comment]
So in this case, I'm referring to terms that appear specifically in the terms/definitions style of the rule book. For example, the [Material and Questions terms](https://github.com/gryphonshafer/Quizzing-Rule-Book/blob/2a2ff6512de72ba364d921930d2d267996be1485/content/rule_book/material_and_questions.md?plain=1#L5-L30) that appear near the beginning of that section. During the automated build process, terms might be left in place, filtered, or migrated to a single glossary at the end, depending on [the `builds` configuration](https://github.com/gryphonshafer/Quizzing-Rule-Book/blob/2a2ff6512de72ba364d921930d2d267996be1485/config/app.yaml#L36-L58).

At some point during the v1 work, I setup a means by which all terms that appear in the content that are defined with a terms/definitions block somewhere get italicized. But the resulting output seemed more difficult to read in many places due to the extensive amount of terms used therein. So I backed out that change.

So it may be that the way things are now is ideal, but I filed this ticket more as a "be sure the RC at least talks about it" sort of thing.

**Comment by jswingle** [comment]
What about underlining the words? I don't necessarily think this, or italicizing for that matter, would be all that distracting (although I'll just take your word on the italics since you've already seen it...). It's not like the rulebook is intended for sitting by the fireside and reading, a bit of notation isn't a bad thing even if it makes the text look a little less cute.

I think that in digital versions of the document it would be great to hyperlink to the Definitions section. Hyperlinks are basically just an underline plus blue color, so if we have the digital version of the rulebook with hyperlinks, the printed version would be the same but just with black text.

**Comment by gryphonshafer** [comment]
Unfortunately, everything I tried made the text far less readable, just due to the shear number of words/phrases that match terms. I tried italic, underline, bold, and light-dashed underlines. The only style that didn't look awful was to slightly change the color from solid black to something like #666. It was enough that you could tell something was up but not enough that it would interrupt flow. Making these internal hyperlinks should be fairly easy, though. It's really just a question of the style, which (at least from my own experience) felt like it needed to be limited to lightening up the black into a mid-dark gray.

A counter thought: Maybe we do away with the PDF file entirely? I mean, anybody who wants a PDF can load the HTML in a browser and print to PDF. If someone wants a table of contents with page numbers, they can easily load the HTML into Word and generate such things. Maybe we decide to nuke all options except the HTML build, and then we setup internal links for terms, leaving the text as black. And if someone wants something different, they can edit the CSS. The CSS right now is simple and small. I could put up at the top of it the most commonly expected custom edits.

I mean, realistically, the average quizzer/coach isn't going to know how to edit the CSS, but chasing preferences for a universal audience isn't realistic either.

**Comment by jttower** [comment]
I think it's fine to get rid of the PDF like you said.  I do think we need to add a Table of Contents, though.  I know you told me how to generate my own, Gryphon, but I don't think most people will go to the trouble, and a Rule Book without an accurate Table of Contents is not user-friendly at all.  I know a lot of you guys are digital now so it's easy to search, but our district is still using printed paper rule books, and when looking for a rule during a challenge, things can get pretty long and frustrating without a TOC.

**Comment by jswingle** [comment]
+1 that the printed version of the rulebook needs a Table of Contents and pagination and this needs to be easily accessible. The pagination is not a complicated process to do manually and we should plan on making a downloadable .docx/pdf after the merge from integration each year.

**Comment by gryphonshafer** [comment]
The TOC and pagination work is completed and in "standby" mode. I've built the functionality as a separate GitHub Action available in the Marketplace that can be integrated into this project (when the time right). Here's a preview:

https://github.com/gryphonshafer/test-book

Integration will involve ripping out all the existing code here (not content), adding a reference and settings to the Action, and then some minor technical-only edits to the content. Therefore, I think it's best to consider performing this work immediately after the `integration` branch is merged with `master`.

Note this is mostly covered under ticket #112. So I think this ticket should probably just be closed. The only consideration here would be to try some clever way to visually markup terms, but everything I've tried looks awful. So I think it was a bad suggestion on my part.

**Comment by ARMediting** [comment]
I vote we keep a PDF. Not everyone who wants the rulebook is going to know how to print to PDF, and the process sounds hard to do on a phone. Can't PDFs link to other sections inside it? I know Word docs can. 

But if we running into reading problems because of the number of terms to be marked, I'd vote for a glossary without links. People are just going to have to learn the terms.

**Comment by jswingle** [comment]
Revisiting this issue and closing it out as redundant with issue #112 

The idea of removing the PDF option could be revisited in a separate issue if desired. I personally think having the PDF option is necessary.
