### ISSUE TITLE
Scoreboards Mandate

### ISSUE THREAD

**Issue by ZacharyTinker** [gryphonshafer/Quizzing-Rule-Book#58]
> An unofficial scoreboard must be maintained in full view of the audience at all times or the score read at the beginning of each timeout.

Very rarely will districts have scoreboards available, let alone enough for each room. The same goes for IBQ. Flipping these so that the easier of the two option is addressed to the reader first, or removing scoreboards entirely and making it a "nice thing to have" would be better options in my opinion. Maybe it could be a best practice for IBQ, but I lean more towards its removal from the Rule Book altogether.

**Comment by scottpeterson** [comment]
I would agree. Considering it's largely ignored anyway.

**Comment by josiah-leinbach** [comment]
I also agree. The rulebook should be enforced in its entirety, and trying to enforce this would be a disaster, in my opinion, given the paucity of scoreboards out there. I don't even know if Great Lakes has one in the whole district.

Therefore, I propose striking the following sentence from 7.6 "Equipment": 

> An unofficial scoreboard must be maintained in full view of the audience at all times or the score read at the beginning of each timeout.

**Comment by josiah-leinbach** [comment]
I will clarify and add that I am not that opinionated about whether to strike "or the score read at the beginning of each time out" as well.

**Comment by jttower** [comment]
It is mentioned in 2.2.3 under Scorekeepers that it is their responsibility to read the score at the beginning of each timeout when there is no scoreboard, so I agree we can strike the whole sentence from 7.6.  

In practice, quizzers and coaches have the ability to ask for a score check at any point between questions, although I don't think this is outlined anywhere in the RB.  Maybe that can go in Best Practices?

**Comment by jswingle** [comment]
Possibly it could go in Best Practices, but I think it may fit better as a rule just so the rulebook includes all of the various things that are expected to be asked of the officials. It's the "ask and you will receive" rule: anyone in the room who's not just an audience member may, at any point in time between questions, ask for the score... and it will be given to them.

On the other hand, when it comes to the "read the score before the timeout" part, I think _that_ is better handled as a Best Practice. It shouldn't be considered protestable if a scorekeeper fails to do it, and the right way to handle a scorekeeper who fails to do it is for a coach to simply ask for the score.

**Comment by jswingle** [comment]
Worth considering: in issue #71 we are talking about the necessity for either _all_ rooms in a given bracket to have recording devices present, or _none_. This maintains parity between quiz rooms.

A similar argument could be advanced with regard to scoreboards _that show the timer._ A simple scoreboard by itself doesn't affect the competition, but if the 30 second timer is visible to the quizzer, this can affect the way quizzers answer questions. The rulebook doesn't specify whether the timer should be visible or invisible to the quizzer (and in my opinion it shouldn't), but if there IS going to be a visible timer on a scoreboard in one room, it should be visible in all rooms.

**Comment by ARMediting** [comment]
I think that's fair, but I'm worried about practicality. If one room has something like MatchMaker being projected to a screen, and another room doesn't have space for that, what options are available?

**Comment by jswingle** [comment]
@ARMediting I'm not super knowledgeable about MatchMaker. Can the timer be hidden? If so, problem solved.

**Comment by ARMediting** [comment]
@jswingle I don't know, but I can try to find out.

Also, I'm in favor of keeping the rule about reading scores after a timeout. This stems from having trouble following the score at a previous Internationals when sitting far in the back of a large room and watching the livestream, because the score wasn't being announced.

**Comment by kclimenhaga** [comment]
> Also, I'm in favor of keeping the rule about reading scores after a timeout.

I'm in favour of reading the scores at every timeout, but in our district at least, we have found it much better to read out the scores before a timeout than after. The reason for this is that if for any reason there is a mistake in the scores (either the official one or one of the coaches'), it's better to sort that out before having the timeout. That way, coaches will be coaching their teams based on an accurate score.

No opinion on whether it needs to be a rule or a best practice. I'm leaning towards "it should be a rule but not protestable" if there's a way to write that.

**Comment by ARMediting** [comment]
On behalf of the Rules Committee:

During our meeting on 9/12/2022, the Rules Committee voted 5-0 to delete the sentence “An unofficial scoreboard must be maintained in full view of the audience at all times or the score read at the beginning of each timeout" from the rulebook, the second paragraph of 8.6.

For more information on the rulebook Change Management Process, please visit: https://github.com/gryphonshafer/Quizzing-Rule-Book/blob/master/content/rule_book/change_management.md

In our discussion, we noted that 8.6.'s current wording could open the door for protests just because a score wasn't read at the right time, which we didn't want. Also, language about reading the score before a timeout still exists at 3.2.3.: 

> 
> 3.2.3. Scorekeepers (SK)
> 
> The scorekeeper will:
>     ...
>     Either read the score or have the score ready to be read at the beginning of timeouts when there is no scoreboard

We do, however, want to promote more frequent score updates, to make the quiz easier to follow and more enjoyable for the audience. Though we don't want to mandate a specific spot in the quiz when the score must be given, the flow of a quiz may mean the score is left out.

Currently, the rulebook contains no language permitting coaches or captains to request the score at any time, though it is standard practice. We saw inserting such language in this issue to be reaching outside the issue's scope, though we'd certainly like to continue the discussion.
