### ISSUE TITLE
Flip rule book to prohibit by default unless explicitly allowed

### ISSUE THREAD

**Issue by gryphonshafer** [gryphonshafer/Quizzing-Rule-Book#62]
The rule book is generally interpreted now as if something isn't prohibited, it's permissible. There's an idea to flip that explicitly (via a rule book clause) to prohibit by default unless explicitly allowed. If we make this flip, many practical failures in process that we haven't the forethought to predict could be prohibited, but it would mean we'd need to check through the rule book to ensure everything permissible is explicitly allowed in the text.

This may be a good idea in principle that would explode the rule book in practice. So great care and consideration should be taken before embarking on this path.

**Comment by kclimenhaga** [comment]
If we did add wording like this, I think we would need to include a point about any exceptions being at the QM's discretion. There are a lot of unpredictable situations (for example, I have been in a quiz where a quizzer had a medical emergency during the quiz) where officials in the room need to have the authority to allow exceptions to the rules. In general, I suspect it is better to leave it as is.

**Comment by jswingle** [comment]
One time a QM in PNW had to invent a new rule on the spot, when during an overtime every single quizzer on both teams was either quizzed or erred out, with the score tied. I think she ended up just putting everyone back in until the tie resolved.

There is no rule specifically allowing this, but if I am QMing and I cannot clearly hear what a quizzer is saying, I will motion my hand to my ear and indicate I can't hear them. This rarely happens, and you could argue it's against the letter of the rules, but it's not against the spirit of the rules, and I doubt any coach would shake a stick at it. I don't think it would be in the spirit of the rules for me to say "Again" either.

I don't think either of these things need to be defined in the rulebook at all. It's good for the rulebook to leave room for prudence in unusual circumstances, particularly ones that are external to quizzing itself such as the venue or technology. As a theoretical example, a suddenly malfunctioning microphone in a large room with a high ceiling could be grounds for throwing out a question, even though normally we would say the responsibility is on the quizzer to make their voice heard.

**Comment by gryphonshafer** [comment]
I do the ear thing myself. I do it not to prompt but to actually try to hear better, but if it's a prompt, I kinda don't feel bad about it.

**Comment by josiah-leinbach** [comment]
This appears to be like the "regulative principle" vs. "normative principle" debate in theology (e.g. corporate worship, church government, etc.), which, while intriguing in its own right, does not appear to fix any existing, defined, problems; or at least any existing and defined problems that cannot be addressed by more targeted rule changes, like many already under discussion. If we are striving for more consistency, that can be better accomplished through well-written rules and a hermeneutical consensus that arises from discussion, as opposed to stating it in the rulebook. We are doing both of these in the course of this revision process.

Furthermore, a "regulative principle" interpretation of the rulebook produces as many interpretative difficulties as a normative approach. By way of the analogy I mentioned earlier, there are debates amongst those who adhere to the regulative principle of worship as to what is actually permitted. For example, does Scripture permit the singing of non-Psalmodic hymns, even those found in Scripture (e.g. Zechariah's song in Luke 1:68-79)? Or does Scripture permit the use of musical instruments, or must everything be sung _a cappella_? And if it permits instruments, which ones? There exists a variety of opinions on these matters, and the regulative principle has not resulted in a better consensus than its interpretative counterpart. Permissions are no less prone to abuse or faulty interpretation than prohibitions.

We must at some level rely on the officials' and districts' prudence in applying the rules to their particular circumstances, even on a quiz-by-quiz basis if needed. There are simply too many possible situations that could happen, and what might be good to do in one would not be good in another.

But regardless, is anyone proposing something more specific than a general question about interpretation?

**Comment by jswingle** [comment]
@gryphonshafer Care to progress this issue any further or propose a rule? I'll be honest: I'm not sure there needs to be a rule added to this effect.

I think there may be individual instances where officials are likely to go beyond the rulebook in one area or another, and we may want rules targeting THOSE SPECIFIC scenarios. For example: "The quizmaster may use the following prompts, _and only the following, and they must be stated verbatim to what's in the rulebook_" or something like that. But I think a general rule of "only what the rulebook says is permitted" leads to a very undesirable scenario where QMs feel they have to be robots instead of adhering to common prudence.

**Comment by gryphonshafer** [comment]
> Care to progress this issue any further or propose a rule?

Not really. Making this change with care would require a massive overhaul of the rule book, because the current version doesn't follow this pattern. I only submitted this issue so there'd be consideration of the philosophy.

**Comment by jswingle** [comment]
@gryphonshafer OK. I am going to move to close it out then, since there's nothing concrete we can consider at the time. But I trust you know that doesn't mean I'm dismissive of the point you're making! As I stated in my above post, I think this philosophy may be more effective if we apply it at specific targets where we think an official may be likely to transgress what the rulebook allows.

**Comment by ARMediting** [comment]
On behalf of the Rules Committee:

During our meeting on 9/12/2022, the Rules Committee voted 5-0 to close this issue. This means we've examined the discussion and decided that nothing ought to be changed at this time.

The concept Gryphon proposes can be brought up again, but since no one suggested any new text for the rulebook implementing the proposal, we deemed it not worth current consideration.

For more information on the rulebook Change Management Process, please visit: https://github.com/gryphonshafer/Quizzing-Rule-Book/blob/master/content/rule_book/change_management.md
