### ISSUE TITLE
Minor Typos in 2.2.1 and 3.2.2 of Version 3dcc7f8, dated 2021-03-04 18:20:11 GMT

### ISSUE THREAD

**Issue by Philip-Osterlund** [gryphonshafer/Quizzing-Rule-Book#76]
Section 2.2.1, bullet 2 reads,
   "Speak in such as a way as..."
It should read,
   "Speak in such a way as..."

---
Section 3.2.2 "3-Team 20-Question" Quiz, Paragraph 2 Sentence 3 reads,
   "If question 1 to 15 is erred, the next question number will be a toss-up question."
Suggested modification:
   "If question 1 to 15 is erred, the next numbered question will be a toss-up question."

This suggested terminology does not match up with the ES variable definition, but it does with English grammar.  The question has a number associated with it, but the number itself is not a question.

**Comment by gryphonshafer** [comment]
The first note is clearly a grammatical error, and as such, I agree it should be fixed (and could be done in v1, assuming agreement from the other committee members). I'm marking this ticket as part of a milestone for such.

The second note I agree with, but it's potentially a bit more complex of a situation. I'm OK with the suggested "the next numbered question will be" phrase, but it could infer that there may be a "non-numbered" question interstitial. I think then instead we should say either:

- If question 1 to 15 is erred, the next question will be a toss-up question.
- If question 1 to 15 is erred, the next question will be a numbered question and a toss-up question.

**Comment by scottpeterson** [comment]
I think `If question 1 to 15 is erred, the next question number will be a toss-up question` is clear as-is.

**Comment by scottpeterson** [comment]
Though I think both of Gryphon's proposed re-writes are clearer, if only incrementally so.

**Comment by zctinker** [comment]
I am always in favor of the clearer wording, no matter how small. 

I would say that 
`If question 1 to 15 is erred, the next question will be a toss-up question.`
is a definition that would fit questions 1-20, including, with A's and B's omitted of course. 

since that seems like it may cause some confusion in the way of people asking "why doesn't it work for numbered questions 16-20"

My vote would then be for.
`If question 1 to 15 is erred, the next question will be a numbered question and a toss-up question.`
