### ISSUE TITLE
Rephrasing in Timeliness section

### ISSUE THREAD

**Issue by ghost** [gryphonshafer/Quizzing-Rule-Book#80]
Section 3.7. Timeliness, paragraph 4
Current reading: "If any number of members of a team is late, the quiz will start on time."
Proposed reading: "If at least one member of each team is on time, the quiz will start on time."

The current reading gives the possibility that all team members are late, and yet the quiz starts on time.

**Comment by scottpeterson** [comment]
It's written correctly. A quiz will start on time even if an entire team is late.

**Comment by zctinker** [comment]
Not disagreeing, but what would be the method of allowing the whole team to join say at question 8? Would a new quiz have to be used (assuming each room was using the same quiz for that round) picking up at question 8? Personally, I've never thought that through completely.

**Comment by scottpeterson** [comment]
well I hope synchronized sets are going away, but good point raised. idk? Obviously if the team is 10 min late they cannot join.

But < 10 min late + synchronized sets? I mean, than can only have potentially heard questions already asked in other rooms....are synchronized sets usually in the same order (questions 1-x each quiz)?

Actually I think I'm overthinking this. There's nothing about synchronized sets in the rule book. If a district/meet uses them, they need to handle the implications they have introduced. I don't think we can handle all potential implications here of meets being run in ways not specified in the rule book.

**Comment by zctinker** [comment]
I would counter there's nothing in the rulebook about asynchronized sets either.

**Comment by zctinker** [comment]
Agreed, we don't need to have a line about every scenario, but it does leave this as a possible gap. I am okay with districts having to sort it out themselves, until/unless we find a perfect line to fill that gap.

**Comment by scottpeterson** [comment]
Basically, a team being late should NEVER affect a meet's schedule.

If synchronized sets pose an issue, then a local rule should be stated "Any team arriving after the start of the quiz forfeits"

Any other way of handling it removes any penalty of being late (unless you dock them something like 10 points per question already asked, but then restart the quiz with a replacement question set). Which feels tremendously kludgey.

**Comment by zctinker** [comment]
Agreed. The penalty has to be there. Perhaps a rule should be added in v2 regarding question sets saying all rooms must have unique question sets. 

Of course this would apply to IBQ specifically, and is something that already happens at IBQ, but would then eliminate any concern. Perhaps under 7.5. Quiz Question Selection

**Comment by gryphonshafer** [comment]
Good points all around. Clearly, this isn't something that should be in scope for v1. We'll triage it for v2 after ratification.

**Comment by Philip-Osterlund** [comment]
What ever happened to the rule that "no question should be asked more than twice in the quiz meet"?
In generating quizzes for the district quiz meet, in the early quiz meets I generally have a few questions that are asked twice, even with synchronized quizzes (although I move most duplicated questions to spare quizzes, and they likely are not asked a second time.)

I'm not sure how many quizzes are generated at IBQ, but avoiding asking the same question more than twice may be difficult.

**Comment by scottpeterson** [comment]
The 2018 RB says this specifically for Internationals `A question can be used multiple times in any part of the International Finals.`   And mentions nothing pertaining to non-Internationals. 

So we just removed it.

**Comment by scottpeterson** [comment]
That rule changed between the 2011 and 2013 rule books.

**Comment by gryphonshafer** [comment]
I think there's value in writing up the question selection preference criteria as a Best Practice (maybe in scope for v2).

**Comment by kclimenhaga** [comment]
Since IBQ uses asynchronized sets, I don't think we need to change the rulebook to account for them. If a team really wants to spy on another quiz to get questions, they could send one member of the team instead of the whole team. 

For local quizzing, there will be so many unique situations about why a team is late that I don't think it makes sense to specify a rule for this either. 

Also, synchronized sets may have gone away at IBQ, but some districts don't have as reliable of Internet as PNW (or as tech-savvy table staff) and still rely a lot on paper, so we are still using synchronized sets for the foreseeable future. (Just as an aside)

**Comment by gryphonshafer** [comment]
Just because I'm a pedantic nerd: Asynchronized sets don't require Internet or software. If quizzes are to be centrally pre-planned, asynchronized sets just requires more preparation time, but nothing special beyond that. And there's nothing that requires centrally pre-planned sets. Individual QMs could pre-package their own quizzes. Synchronized sets is purely a time-saving mechanism for pure-paper-based meets with centralized quiz preparation.

And as an aside: Not that I think any quiz team would do this, but it wouldn't be difficult in a synchronized questions world for a team to send a non-team spy to relay questions via text or whatever, then the team calls a time-out, catches up on the intel, then dominates the next couple+ questions. Hyper-unlikely, though. And probably better to cover this via some sort of general "spirit of Quizzing" clause than adjusting the late clause.

**Comment by kclimenhaga** [comment]
Rules Committee voted 10/04 to leave the current wording as is. A quiz will start on time even if one entire team is late. 

On behalf of the Rules Committee, this issue is closed.

**Comment by jswingle** [comment]
Looks like this didn't get closed on 4/28, so closing it now.
