### ISSUE TITLE
Married Clause

### ISSUE THREAD

**Issue by Philip-Osterlund** [gryphonshafer/Quizzing-Rule-Book#93]
The old rule books had a statement that quizzers must not be married.  This seemed like an odd statement, and perhaps needed to go by the way-side.  It's not in the 2018 rule-book.

Why was the rule there?  Why was it removed?

**Comment by josiah-leinbach** [comment]
I have no knowledge of the rule's history, but I would think the logic behind it is that a married quizzer (a very rare circumstance, just given the age/graduation cut-off for quizzing) would be in a categorically different life-stage compared to their non-married quizzing peers, perhaps making for some awkward or at least difficult scenarios.

Also, the rule strikes me as something that was probably instituted because of a one-off situation that involved a married quizzer at some point, the rule being formalized as a sort of "case law" if you will. Whatever the reasons for instituting the rule, its removal will allow districts to handle these potential situations on a case-by-case basis.
