### ISSUE TITLE
Section 1.2.2.2 Negative MA answers

### ISSUE THREAD

**Issue by Philip-Osterlund** [gryphonshafer/Quizzing-Rule-Book#95]
Request to remove the restriction that MA questions cannot have a "negative" answer.

Statement: Paul tends to write many good arguments in negative form, many of which would make good multiple-answer questions.  Yet removing the possibility of MA questions for these passages removes a lot of good questions.  (Paraphrase of Josh Jetto)

**Comment by jswingle** [comment]
This rule is actually not specific to MAs, and is confusing because it's stated a second time in the MA section. Here are the relevant portions of the rulebook:

Under 1.2.2.2:

`In addition, an MA question is invalid if 1 of the listed answers to the multiple answer's questions is a "negative" answer. A "negative" answer is an answer used to contrast another answer or an answer that does not answer the question, such as an answer that begins with the words or similar words to "not" or "neither".`

Under 1.2.3:

Talking about questions in general, and not just MAs, it says a question must be declared invalid `if the question is not answered`

Then, under example 1.2.3.1:

`To help illustrate more the idea of "if the question is not answered", consider a scenario where the question asks, "What is good?", and the answer states what is not good. In this case, the question is not answered and is `tricky or misleading.

---

I also really do not like this rule, for several reasons:

**1. It's difficult to define what a "negative answer" is.** There are plenty of circumstances where this is not straightforward. For example, from 1 Cor. 1, where it states "Not many of you were influential," is it valid to ask the question "Who were influential?" The answer implies that there are at least some of the Corinthians who WERE in fact influential, but the phrasing is negative. I've run into many similar scenarios since this rule was written - scenarios where I frankly have no clue how to apply the rule. Even the best rules have corner cases where they're difficult to apply, but that's precisely why we should only be including rules if they serve a significant purpose and add a lot to quizzing. Which leads me to the next point...

**2. I've never seen a quizzer get confused by negative answers in questions.** I wrote my own questions and used them as a QM for some 5 or so years before this rule was added. I frequently wrote negative answers to my questions, and I never noticed them trip up a quizzer or got any challenges or questions about them. So, as far as my subjective experience is concerned, this rule is not solving any real problems of quizzing, it's just adding extra problems to quizzing.

**3. Grammatically speaking, these answers DO in fact answer the question.** There is nothing grammatically wrong or misleading about answering a question in the negative. We do it in everyday speech all the time. And in plenty of circumstances, the question is significant. E.g. from Hebrews 4:13, "What is hidden from God's sight?" A: "Nothing in all creation." This is a beautiful and significant question, though it is answered negatively.

**4. This rule makes reference questions harder on the quizzers.** A likely unintended consequence of this rule is that we now have to count quizzers wrong if they mess this rule up when forming their question on a prejumped reference question. The quizzer's question needs to be a valid question, after all. So if the CVR question is "you are not what?" and the quizzer wants to make the question shorter (usually a smart and safe choice), they might answer "you are what?" and be counted incorrect because their question is invalid. We want reference questions to test the quizzer's knowledge of the material, not the intricacies of the _rulebook._

**5. Scripture says a lot of things by means of stating the negative, and we can't ask good questions about this stuff anymore because of this rule.** For example, you can no longer ask about the famous Romans 8:38-39, "What will be able to separate us from the love of Christ?" A: "Neither death nor life..." etc. even though it seems obvious to me that this is a great and spiritually significant MA which wouldn't confuse any quizzers who know the verses.

**Comment by gryphonshafer** [comment]
I agree with everything Jeremy wrote. Burn this rule with unquenchable fire.

Quizzing encourages memorization of the content. We don't require quizzers to interpret the Scripture. And yet the quizzers almost universally have a stronger understanding of the interpretation of Scripture than the average Christian adult, which demonstrates to me the illumination of the Holy Spirit.

**Comment by jswingle** [comment]
On behalf of the Rules Committee, I am closing this issue as it is identical to another one: https://github.com/gryphonshafer/Quizzing-Rule-Book/issues/105

I have linked to this discussion in that issue, so all the discussion had here can still be under consideration.
